import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";
import { ToastAction } from "@/components/ui/toast";
import { useToast } from "@/components/ui/use-toast";
import { MainLayout } from "~/components/MainLayout";
import { Button, buttonVariants } from "@/components/ui/button";
import { Logo } from "~/components/Logo";
import { LogoTypography } from "~/components/LogoTypography";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const { toast } = useToast();
  const {data} = api.product.getAll.useQuery();
  return (
    <>
      
      <Head>
        <title>FusedParts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="apple-mobile-web-app-title" content="FusedParts" />
        <meta name="application-name" content="FusedParts" />
        <meta name="msapplication-TileColor" content="#4ad59c" />
      </Head>
    
      <MainLayout>
        <section className="flex max-w-[980px] flex-col items-start gap-2 px-4 pt-8 md:pt-12">
          <h1 className="scroll-m-20 text-2xl font-bold tracking-tight lg:text-5xl">
            Build your dream keyboard.
          </h1>
          <p className="text-xl text-muted-foreground">
            Create the ultimate keyboard using the materials of your choice.
          </p>
          <div className="flex w-full items-center space-x-4 pb-8 pt-4 md:pb-10">
            <Link
              href="/create/keyboard"
              className={buttonVariants({ variant: "default" })}
            >
              Get Started
            </Link>
            <Button variant="secondary">Learn more</Button>
          </div>
          <h1 className="scroll-m-20 text-2xl font-bold tracking-tight lg:text-3xl">
            Community Created
          </h1>
          <p className="text-xl text-muted-foreground">
            Keyboards created by other people!
          </p>
        </section>
      </MainLayout>
    </>
  );
};

export default Home;
